* Emacs Startup
When testing changes to the Emacs configuration it is useful to
be able to restart Emacs from within Emacs. The following allows to
restart Emacs when C-x C-c (normally bound to save-buffers-kill-Emacs)
is invoked with a universal argument.

Note that when we restart Emacs, all open files and frames are
restored (courtesy of the desktop package if installed). We also retrieve the
initial command line arguments. ~restart-emacs~ doesn't do this as
there's no platform independent way for doing it. Note that
~command-line-args~ is not sufficient as many arguments are deleted
while being processed by the Emacs C code (for instance ~--debug-init~ )
I'd still think that it would be better than completely ignoring them,
but I'm not the author of the ~restart-emacs~ package. Here I collect
arguments from the ~/proc~ file system, I only care about Linux anyhow.

#+BEGIN_SRC emacs-lisp
  (defun neo/emacs-args ()
    (with-temp-buffer
      (insert-file-contents "/proc/self/cmdline")
      (split-string (buffer-string) "\0" t)))

  (defun neo/restart-emacs-or-exit (arg)
    (interactive "P")
    (if arg
        (restart-emacs (cdr (neo/emacs-args)))
      (save-buffers-kill-emacs)))
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (use-package restart-emacs
    :bind
    ("C-x C-c" . neo/restart-emacs-or-exit))
#+END_SRC
